import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
    "./stitch/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#6c5c43",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e5e2dd",
        "surface-variant": "#e5e2dd",
        "on-error": "#ffffff",
        "outline-variant": "#c2c8bf",
        "on-primary-container": "#98ba99",
        "on-tertiary": "#ffffff",
        "secondary-container": "#f2ddbd",
        "on-secondary-container": "#706047",
        error: "#ba1a1a",
        "on-primary-fixed": "#03210b",
        "tertiary-fixed": "#f4dfcb",
        "on-tertiary-fixed": "#241a0e",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#2f4e33",
        "secondary-fixed": "#f5e0c0",
        "inverse-surface": "#31302d",
        "on-secondary-fixed-variant": "#53452d",
        "surface-container-lowest": "#ffffff",
        surface: "#fcf9f4",
        tertiary: "#382c1f",
        "surface-container-high": "#ebe8e3",
        outline: "#737971",
        "surface-container": "#f0ede8",
        "tertiary-container": "#4f4234",
        "surface-tint": "#47664a",
        "on-background": "#1c1c19",
        "inverse-primary": "#adcfad",
        "inverse-on-surface": "#f3f0eb",
        "tertiary-fixed-dim": "#d7c3b0",
        primary: "#17341c",
        "primary-container": "#2d4b31",
        "primary-fixed-dim": "#adcfad",
        "surface-dim": "#dcdad5",
        "on-tertiary-fixed-variant": "#524436",
        "surface-container-low": "#f6f3ee",
        "on-secondary-fixed": "#241a06",
        "surface-bright": "#fcf9f4",
        "on-tertiary-container": "#c1ae9c",
        "primary-fixed": "#c8ecc8",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#d8c4a5",
        "on-surface": "#1c1c19",
        "on-error-container": "#93000a",
        background: "#fcf9f4",
        "on-surface-variant": "#424841",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
